import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  Activity, AirVent, Bell, ChevronDown, CloudRain, Droplets, Eye, Gauge,
  Globe2, HeartPulse, Leaf, MapPin, Menu, Moon, MoreHorizontal, Navigation,
  Palette, Plus, Search, Settings2, ShieldAlert, ShipWheel, Sun, Sunrise, Sunset,
  Thermometer, UserRound, Waves, Wind, X, Zap
} from "lucide-react";
import { fetchWeather, formatDay, formatHour, searchWeatherLocations, weatherIcon } from "@/weatherService";
import "@/App.css";

const personas = [
  { id: "fitness", label: "Outdoor fitness", short: "Fitness", icon: Activity, color: "orange", note: "Your best window for movement" },
  { id: "health", label: "Health & wellness", short: "Health", icon: HeartPulse, color: "rose", note: "Breathe easier, plan smarter" },
  { id: "travel", label: "Travel", short: "Travel", icon: Globe2, color: "blue", note: "Know before you go" },
  { id: "beach", label: "Beach & surf", short: "Beach", icon: Waves, color: "cyan", note: "Read the rhythm of the coast" },
  { id: "family", label: "Family", short: "Family", icon: UserRound, color: "violet", note: "Good days start outdoors" },
  { id: "agriculture", label: "Agriculture", short: "Farm", icon: Leaf, color: "green", note: "Signals for every growing day" },
  { id: "commute", label: "Daily commute", short: "Commute", icon: Navigation, color: "amber", note: "Leave with confidence" },
  { id: "events", label: "Events", short: "Events", icon: Zap, color: "pink", note: "Make plans that hold" },
];

const hours = [["Now", "28°", Sun], ["4 PM", "29°", Sun], ["5 PM", "28°", CloudRain], ["6 PM", "27°", CloudRain], ["7 PM", "26°", CloudRain], ["8 PM", "25°", Moon]];
const days = [["Mon", "31°", "24°", Sun, "8%"], ["Tue", "30°", "23°", Sun, "12%"], ["Wed", "28°", "22°", CloudRain, "58%"], ["Thu", "27°", "22°", CloudRain, "70%"], ["Fri", "31°", "24°", Sun, "18%"]];
const locationCatalog = [
  ["Vijayawada", "Andhra Pradesh, India"], ["Hyderabad", "Telangana, India"], ["New Delhi", "Delhi, India"], ["Mumbai", "Maharashtra, India"], ["Bengaluru", "Karnataka, India"], ["Chennai", "Tamil Nadu, India"], ["Kolkata", "West Bengal, India"], ["Pune", "Maharashtra, India"], ["Visakhapatnam", "Andhra Pradesh, India"], ["Rajahmundry", "East Godavari, Andhra Pradesh, India"], ["Rajamahendravaram", "East Godavari, Andhra Pradesh, India"], ["Kakinada", "Kakinada district, Andhra Pradesh, India"], ["Amalapuram", "Konaseema district, Andhra Pradesh, India"], ["Ravulapalem", "Konaseema district, Andhra Pradesh, India"], ["Mandapeta", "Konaseema district, Andhra Pradesh, India"], ["Ramachandrapuram", "Konaseema district, Andhra Pradesh, India"], ["Mummidivaram", "Konaseema district, Andhra Pradesh, India"], ["Atreyapuram", "Konaseema district, Andhra Pradesh, India"], ["Alamuru", "Konaseema district, Andhra Pradesh, India"], ["Kothapeta", "Konaseema district, Andhra Pradesh, India"], ["Draksharamam", "Konaseema district, Andhra Pradesh, India"], ["Samalkota", "Kakinada district, Andhra Pradesh, India"], ["Peddapuram", "Kakinada district, Andhra Pradesh, India"], ["Pithapuram", "Kakinada district, Andhra Pradesh, India"], ["Tuni", "Kakinada district, Andhra Pradesh, India"], ["Anaparthi", "East Godavari, Andhra Pradesh, India"], ["Rajanagaram", "East Godavari, Andhra Pradesh, India"], ["Jaggampeta", "Kakinada district, Andhra Pradesh, India"], ["Gokavaram", "East Godavari, Andhra Pradesh, India"], ["Seethanagaram", "East Godavari, Andhra Pradesh, India"], ["Devipatnam", "Alluri Sitharama Raju district, Andhra Pradesh, India"], ["Rampachodavaram", "Alluri Sitharama Raju district, Andhra Pradesh, India"], ["Maredumilli", "Alluri Sitharama Raju district, Andhra Pradesh, India"], ["Polavaram", "Eluru district, Andhra Pradesh, India"], ["Kovvur", "West Godavari, Andhra Pradesh, India"], ["Nidadavole", "West Godavari, Andhra Pradesh, India"], ["Tanuku", "West Godavari, Andhra Pradesh, India"], ["Tadepalligudem", "West Godavari, Andhra Pradesh, India"], ["Bhimavaram", "West Godavari, Andhra Pradesh, India"], ["Palakollu", "West Godavari, Andhra Pradesh, India"], ["Narasapur", "West Godavari, Andhra Pradesh, India"], ["Eluru", "Eluru district, Andhra Pradesh, India"], ["Guntur", "Andhra Pradesh, India"], ["Tirupati", "Andhra Pradesh, India"], ["Goa", "India"], ["London", "England, United Kingdom"], ["New York", "New York, United States"], ["San Francisco", "California, United States"], ["Dubai", "United Arab Emirates"], ["Singapore", "Singapore"], ["Tokyo", "Japan"], ["Sydney", "New South Wales, Australia"], ["Paris", "France"], ["Toronto", "Ontario, Canada"], ["Berlin", "Germany"], ["Cape Town", "South Africa"], ["Bangkok", "Thailand"], ["Bali", "Indonesia"]
];
const glassGlobeUrl = "https://static.prod-images.emergentagent.com/jobs/242c255e-7b43-47bc-afec-4341caa17fe3/images/844aec80732e2009971269792101b9f4cc7840b02f2f594e23e10d8c446ed047.jpeg";
const defaultPlace = { id: 1264527, name: "Rajahmundry", admin1: "Andhra Pradesh", country: "India", latitude: 17.0005, longitude: 81.8040, timezone: "Asia/Kolkata" };
const mockWeather = { timezone: "Asia/Kolkata", source: "fallback", current: { temperature_c: 28, feels_like_c: 30, humidity: 72, wind_kmh: 14, precipitation_mm: 0, weather_code: 2, is_day: 1, condition: "partly-cloudy", condition_label: "Partly cloudy" }, hourly: [], daily: [] };

function IconButton({ children, label, onClick, testid }) { return <button className="icon-button" aria-label={label} title={label} data-testid={testid} onClick={onClick}>{children}</button>; }

function LocationSearch({ query, setQuery, results, onSelect, onClose, searching }) {
  return <div className="location-modal-backdrop"><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="location-modal" data-testid="location-search-modal"><div className="location-modal-head"><div><span className="eyebrow">LIVE LOCATION SEARCH</span><h2>Where next?</h2></div><IconButton label="Close location search" onClick={onClose} testid="close-location-search-button"><X size={20}/></IconButton></div><div className="location-search-field"><Search size={18}/><input autoFocus value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search any Indian city or place" data-testid="location-search-input"/><kbd>⌘ K</kbd></div><p className="location-search-note">Search powered by Open-Meteo geocoding. Select a result to load live weather.</p><div className="location-results" data-testid="location-search-results">{searching ? <div className="no-location-results" data-testid="location-search-loading"><span className="search-spinner"/> Finding places…</div> : results.length ? results.map((place)=><button key={`${place.name}-${place.latitude}`} onClick={()=>onSelect(place)} data-testid={`location-result-${place.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`}><span className="result-pin"><MapPin size={16}/></span><span><b>{place.name}</b><small>{[place.admin1, place.country].filter(Boolean).join(", ")}</small></span><ChevronDown size={16}/></button>) : <div className="no-location-results" data-testid="no-location-results"><Search size={18}/><span>{query.length > 1 ? "No places found. Try another city or spelling." : "Start typing a city or region."}</span></div>}</div><div className="location-modal-foot"><Globe2 size={14}/> Live weather by Open-Meteo · Geocoding data by GeoNames</div></motion.div></div>;
}

function Onboarding({ onChoose, onSkip }) {
  const [selected, setSelected] = useState(["fitness"]);
  const toggle = (id) => setSelected((items) => items.includes(id) ? items.filter((x) => x !== id) : [...items, id]);
  return <div className="onboarding-backdrop"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="onboarding">
    <div className="onboarding-mark"><Sun size={22} /></div><span className="eyebrow">MAUSAM / YOUR WEATHER INTELLIGENCE</span>
    <h1>How do you use<br /><em>weather?</em></h1><p className="onboarding-copy">Tell us what matters to you. We&apos;ll make your forecast feel personal.</p>
    <div className="persona-grid">{personas.map(({ id, label, icon: I }) => <button key={id} className={`persona-option ${selected.includes(id) ? "selected" : ""}`} data-testid={`onboarding-persona-${id}`} onClick={() => toggle(id)}><I size={18} /><span>{label}</span>{selected.includes(id) && <span className="check">✓</span>}</button>)}</div>
    <div className="onboarding-actions"><button className="text-button" data-testid="onboarding-skip-button" onClick={onSkip}>Skip for now</button><button className="primary-button" data-testid="onboarding-continue-button" onClick={() => onChoose(selected[0] || "fitness")}>Build my dashboard <span>→</span></button></div>
  </motion.div></div>;
}

function WeatherGlyph({ condition, size = 22 }) { const Icon = condition === "sunny" ? Sun : condition === "night" ? Moon : condition === "fog" ? Eye : condition === "storm" ? Zap : condition === "rain" ? CloudRain : AirVent; return <Icon size={size} />; }

function Hero({ dark, location, weather, loading }) { const current = weather?.current || mockWeather.current; const state = current.condition || "partly-cloudy"; return <motion.section layout className={`hero panel weather-${state}`} data-testid="hero-weather-card" data-weather-condition={state}>
  <div className="globe-stage" aria-hidden="true"><div className="globe-halo" /><img src={glassGlobeUrl} alt="" /></div>
  <div className="hero-sky"><div className="sun-disc" /><div className="cloud cloud-one" /><div className="cloud cloud-two" /><div className="hero-lines" /><div className="weather-motion" data-testid="weather-motion" data-weather-state={state}><div className="rain-layer">{Array.from({length:14}, (_,i)=><i key={i} style={{left:`${8+(i*7)%90}%`, animationDelay:`-${(i%6)*.55}s`, animationDuration:`${1.5+(i%4)*.28}s`}} />)}</div><div className="lightning-flash" /></div></div>
  <div className="hero-top"><div><span className="eyebrow light">{loading ? "UPDATING LIVE CONDITIONS" : `LIVE CONDITIONS / ${weather?.source === "open-meteo" ? "OPEN-METEO" : "DEMO FALLBACK"}`}</span><h1 data-testid="hero-location">{location}</h1><p className="hero-condition" data-testid="hero-condition"><WeatherGlyph condition={state} size={16}/> {current.condition_label || "Partly cloudy"} <span>•</span> Feels like {Math.round(current.feels_like_c ?? 30)}°</p></div><div className="hero-temp" data-testid="hero-temperature">{Math.round(current.temperature_c ?? 28)}°<small>C</small></div></div>
  <div className="hero-bottom"><div className="hero-summary"><span className="weather-icon"><WeatherGlyph condition={state} size={30} /></span><span>Good afternoon, Tejeswar <b>👋</b></span></div><div className="hero-metrics">{[[Droplets,"Humidity",`${current.humidity ?? 72}%`],[Wind,"Wind",`${Math.round(current.wind_kmh ?? 14)} km/h`],[CloudRain,"Rain",`${current.precipitation_mm ?? 0} mm`],[WeatherGlyph,"Condition",current.condition_label || "Partly cloudy"]].map(([I, k, v]) => <div className="hero-metric" key={k} data-testid={`hero-metric-${k.toLowerCase().replace(" ", "-")}`}><I size={16} /><span>{k}</span><strong>{v}</strong></div>)}</div></div>
</motion.section>; }

function FitnessCard({ weather }) { const c = weather?.current || mockWeather.current; const score = Math.max(0, Math.min(100, Math.round(100 - Math.max(0, (c.temperature_c || 28) - 23) * 4 - (c.wind_kmh || 14) * .4))); const window = (c.temperature_c || 28) >= 31 ? "Before 8:00 AM" : "Now – 8:00 PM"; return <motion.section layout className="panel lifestyle fitness-card" data-testid="fitness-module"><div className="module-heading"><div><span className="eyebrow orange">OUTDOOR FITNESS</span><h2>Best time to move</h2></div><span className="score orange-score" data-testid="workout-score">{score}<span>/100</span></span></div><div className="run-window"><div><strong>{window}</strong><p><span className="status-dot" /> Derived from live temperature and wind</p></div><div className="runner-visual"><Activity size={42} /><div className="track"><i /><i /><i /></div></div></div><div className="mini-stats">{[[Thermometer,"Temp",`${Math.round(c.temperature_c || 28)}°`],[Droplets,"Humidity",`${c.humidity ?? "N/A"}%`],[Sun,"UV index","N/A"],[Wind,"Wind",`${Math.round(c.wind_kmh || 14)} km/h`]].map(([I,k,v]) => <div key={k} data-testid={`fitness-${k.toLowerCase().replace(" ", "-")}`}><I size={16}/><small>{k}</small><b>{v}</b></div>)}</div><p className="insight"><Zap size={15}/> This recommendation uses live temperature and wind. UV is not supplied by the current weather feed.</p></motion.section>; }

function HealthCard({ weather }) { const c = weather?.current || mockWeather.current; return <motion.section layout className="panel lifestyle health-card" data-testid="health-module"><div className="module-heading"><div><span className="eyebrow rose">HEALTH WEATHER</span><h2>Know your environment</h2></div><span className="score rose-score">LIVE</span></div><div className="health-readings"><div className="aqi-ring"><strong>N/A</strong><span>AQI</span></div><div><b>Feed unavailable</b><p>Air quality is not included in this source</p><div className="progress"><i style={{width:"28%"}} /></div></div></div><div className="health-row"><span><Leaf size={15}/> Pollen <b>N/A</b></span><span><Sun size={15}/> UV <b>N/A</b></span><span><Droplets size={15}/> Humidity <b>{c.humidity ?? "N/A"}%</b></span></div><p className="alert-note"><ShieldAlert size={16}/> AQI, pollen, and UV are ready for an IMD/environmental feed when available.</p></motion.section>; }

function TravelCard({ weather }) { const c = weather?.current || mockWeather.current; const rain = weather?.hourly?.slice(0, 12).reduce((max, h) => Math.max(max, Number(h.precipitation_probability || 0)), 0) || 0; return <motion.section layout className="panel lifestyle travel-card" data-testid="travel-module"><div className="module-heading"><div><span className="eyebrow blue">TRAVEL WEATHER</span><h2>Selected place</h2></div><IconButton label="More travel options" testid="travel-more-button"><MoreHorizontal size={20}/></IconButton></div><div className="travel-main"><div><strong>{Math.round(c.temperature_c || 28)}°</strong><span>{c.condition_label || "Weather"}</span></div><div className="travel-facts"><span><CloudRain size={15}/> {Math.round(rain)}% rain</span><span><Wind size={15}/> {Math.round(c.wind_kmh || 0)} km/h</span></div></div><div className="packing"><span>🧳</span><div><b>{rain >= 50 ? "Keep rain protection accessible" : "Pack for changing weather"}</b><small>Recommendation based on the next 12 hours</small></div><ChevronDown size={17}/></div></motion.section>; }

function BeachCard({ weather }) { const c = weather?.current || mockWeather.current; return <motion.section layout className="panel lifestyle beach-card" data-testid="beach-module"><div className="wave-art"><Waves size={82}/></div><div className="module-heading"><div><span className="eyebrow cyan">OUTDOOR CONDITIONS</span><h2>Read the weather</h2></div><span className="score cyan-score">LIVE</span></div><div className="beach-stats"><span><b>{Math.round(c.temperature_c || 28)}°</b>Air temp</span><span><b>N/A</b>Wave height</span><span><b>{Math.round(c.wind_kmh || 0)} km/h</b>Wind</span></div><p className="tide-line"><span>Water temp <b>Not supplied</b></span><span>Wave data <b>IMD layer ready</b></span></p></motion.section>; }

function GenericCard({ persona, weather }) { const c = weather?.current || mockWeather.current; const rain = weather?.hourly?.slice(0, 12).reduce((max, h) => Math.max(max, Number(h.precipitation_probability || 0)), 0) || 0; const temp = `${Math.round(c.temperature_c || 28)}°`; const rainPercent = `${Math.round(rain)}%`; let config = ["YOUR OUTLOOK", persona.note, "Live weather signals are ready for your plans.", temp, "Live temperature"]; if (persona.id === "family") config = ["FAMILY WEATHER", "Plan the school run", rain >= 50 ? "Rain may affect the school-run window. Check the hourly outlook before leaving." : "The next few hours look comfortable for family plans.", temp, "Live temperature"]; if (persona.id === "agriculture") config = ["FARM WEATHER", rain >= 50 ? "Rain is on the way" : "A calmer field window", rain >= 50 ? "Check soil moisture before scheduling irrigation." : "Current rainfall risk is modest. Use the live outlook to plan field work.", rainPercent, "Rain probability"]; if (persona.id === "commute") config = ["MORNING COMMUTE", rain >= 50 ? "Travel carefully" : "Steady conditions", rainPercent + " rain probability in the next 12 hours. Visibility data is not supplied by this feed.", rainPercent, "Rain probability"]; if (persona.id === "events") config = ["OUTDOOR EVENT", rain >= 50 ? "Plan before the rain" : "Conditions look promising", rainPercent + " rain probability across the next 12 hours.", rainPercent, "Rain probability"]; return <motion.section layout className={`panel lifestyle generic-card ${persona.color}`} data-testid={`${persona.id}-module`}><span className="eyebrow">{config[0]}</span><h2>{config[1]}</h2><p>{config[2]}</p><div className="generic-bottom"><div><b>{config[3]}</b><small>{config[4]}</small></div><div className="spark-bars">{[20,42,31,62,48,78,58].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div></div></motion.section>; }

function Hourly({ weather }) { const rows = weather?.hourly?.length ? weather.hourly.slice(0, 8) : hours.map(([time, temperature, Icon], i) => ({ time, temperature_c: Number.parseInt(temperature), condition: i > 1 ? "rain" : "sunny", precipitation_probability: i === 2 || i === 3 ? 40 : 0 })); return <section className="section-block" data-testid="hourly-forecast"><div className="section-title"><div><span className="eyebrow">THE DAY AHEAD / LIVE</span><h2>Hourly forecast</h2></div><button className="link-button" data-testid="hourly-view-all-button">View 24 hours <span>→</span></button></div><div className="hourly-strip">{rows.map((row, i) => { const label = row.time?.includes(" ") ? formatHour(row.time, weather?.timezone) : row.time; return <div className={`hour ${i===0?"active":""}`} key={`${row.time}-${i}`} data-testid={`hour-${i}`}><small>{label}</small><WeatherGlyph condition={weatherIcon(row.condition, true)} size={22}/><b>{Math.round(row.temperature_c)}°</b><span>{row.precipitation_probability ? `${Math.round(row.precipitation_probability)}%` : "—"}</span></div>; })}</div></section>; }

function Weekly({ weather }) { const rows = weather?.daily?.length ? weather.daily : days.map(([date, high, low, Icon, rain]) => ({ date, high_c: Number.parseInt(high), low_c: Number.parseInt(low), condition: "sunny", rain_probability: Number.parseInt(rain) })); return <section className="panel weekly" data-testid="weekly-forecast"><div className="section-title"><div><span className="eyebrow">EXTENDED OUTLOOK / LIVE</span><h2>Next 7 days</h2></div><IconButton label="More forecast options" testid="weekly-more-button"><MoreHorizontal size={20}/></IconButton></div>{rows.map((row, index) => <div className="day-row" key={`${row.date}-${index}`} data-testid={`forecast-${index}`}><b>{weather?.daily?.length ? formatDay(row.date, weather.timezone) : row.date}</b><WeatherGlyph condition={weatherIcon(row.condition, true)} size={19}/><span className="rain-chance">{Math.round(row.rain_probability || 0)}% rain</span><div className="temp-bar"><i style={{width:`${Math.min(100, Number(row.high_c || 28) + 5)}%`}} /></div><strong>{Math.round(row.high_c)}°</strong><span className="low">{Math.round(row.low_c)}°</span></div>)}</section>; }

function WeatherMap({ location }) { const [layer, setLayer] = useState("Rainfall"); return <section className="panel map-panel" data-testid="weather-map"><div className="section-title"><div><span className="eyebrow">WEATHER LAYERS / LIVE LOCATION</span><h2>Weather map</h2></div><button className="map-location" data-testid="map-location-button"><MapPin size={15}/> {location}</button></div><div className="map-canvas"><div className="map-grid"/><div className="map-road road-one"/><div className="map-road road-two"/><div className="radar radar-one"/><div className="radar radar-two"/><div className="map-pin"><MapPin size={22}/><span>Live</span></div><div className="map-label label-one">Guntur</div><div className="map-label label-two">Eluru</div></div><div className="layer-tabs">{["Temperature","Rainfall","Wind","AQI","Satellite"].map(x=><button className={layer===x?"active":""} key={x} onClick={()=>setLayer(x)} data-testid={`map-layer-${x.toLowerCase()}`}>{x}</button>)}</div></section>; }

function Alerts({ weather }) { const c = weather?.current || mockWeather.current; const isStorm = c.condition === "storm"; const isRain = c.condition === "rain"; return <section className="panel alerts" data-testid="alerts-section"><div className="section-title"><div><span className="eyebrow orange">WEATHER ALERT CENTER</span><h2>Stay weather-aware</h2></div><span className="alert-count" data-testid="alert-count">LIVE</span></div><div className={`alert-item ${isStorm ? "warning" : "info"} alert-feature`} data-testid="severe-weather-alert"><div className="alert-icon"><WeatherGlyph condition={c.condition} size={18}/></div><div><b>{isStorm ? "Thunderstorm conditions" : isRain ? "Rain advisory" : "No severe warning"}</b><p>{isStorm ? "Thunderstorm conditions detected in the live weather feed. Official IMD warnings are not included in Open-Meteo." : isRain ? `${c.condition_label || "Rain"} is currently detected. Check the hourly precipitation outlook.` : "Open-Meteo reports current conditions only; official warnings can be connected from IMD."}</p></div><ChevronDown size={18}/></div><div className="alert-item info"><div className="alert-icon"><ShieldAlert size={18}/></div><div><b>Official warning integration ready</b><p>IMD advisories can be layered here when the official warning feed is available.</p></div><ChevronDown size={18}/></div><button className="outline-button" data-testid="view-alerts-button">View alert sources <span>→</span></button></section>; }

function Recommendation({ persona, weather, location }) { const current = weather?.current || mockWeather.current; const nextRain = weather?.hourly?.slice(0, 12).reduce((max, hour) => Math.max(max, Number(hour.precipitation_probability || 0)), 0) || 40; const hot = Number(current.temperature_c || 28) >= 32; const copy = { agriculture: nextRain >= 50 ? "Rain is likely later today. Check soil moisture before scheduling irrigation." : "A calmer window is ahead. Good conditions to inspect fields and plan irrigation.", fitness: hot ? "Morning conditions are more comfortable for outdoor activity." : "Temperatures and wind look comfortable for a strong outdoor session.", health: "Humidity and UV are the signals to watch before spending time outside.", travel: nextRain >= 50 ? "Rain is expected later today. Keep rain protection accessible." : "A clear travel window is shaping up. Pack light and stay flexible.", family: nextRain >= 50 ? "Rain alerts may affect the school-run window. Leave a little earlier." : "A comfortable outdoor window is opening for family plans.", commute: nextRain >= 50 ? "Rain probability increases later. Consider travelling earlier if possible." : "Conditions look steady for the commute. Visibility should stay comfortable.", events: nextRain >= 50 ? "Outdoor conditions are more favorable before the rain window." : "The outlook is comfortable for an outdoor event." }[persona.id] || "Your weather signals are ready for the day."; return <section className="important-section" data-testid="important-for-you"><div className="important-heading"><div><span className="eyebrow">IMPORTANT FOR YOU</span><h2>{persona.label} intelligence</h2></div><span className="live-chip" data-testid="weather-source-chip">{weather?.source === "open-meteo" ? "LIVE WEATHER" : "DEMO FALLBACK"}</span></div><div className="recommendation-row"><div className="recommendation-icon"><Zap size={19}/></div><div><b data-testid="smart-recommendation">{copy}</b><span>{location} · Based on current conditions and the next 12 hours</span></div></div><div className="recommendation-metrics"><span><CloudRain size={15}/> Rain chance <b>{Math.round(nextRain)}%</b></span><span><Thermometer size={15}/> Temperature <b>{Math.round(current.temperature_c || 28)}°C</b></span><span><Wind size={15}/> Wind <b>{Math.round(current.wind_kmh || 14)} km/h</b></span></div></section>; }

function App() {
  const [personaId, setPersonaId] = useState(localStorage.getItem("mausam-persona") || "fitness");
  const [onboarding, setOnboarding] = useState(localStorage.getItem("mausam-seen") !== "true");
  const [dark, setDark] = useState(false); const [customize, setCustomize] = useState(false); const [mobileMenu, setMobileMenu] = useState(false); const [activeNav, setActiveNav] = useState("Home"); const [showThemes, setShowThemes] = useState(false);
  const [theme, setTheme] = useState(localStorage.getItem("mausam-theme") || "editorial");
  const [selectedPlace, setSelectedPlace] = useState(() => { try { return JSON.parse(localStorage.getItem("mausam-location-place")) || defaultPlace; } catch { return defaultPlace; } });
  const location = selectedPlace.name;
  const [showNotifications, setShowNotifications] = useState(false); const [showProfile, setShowProfile] = useState(false); const [showLocationSearch, setShowLocationSearch] = useState(false); const [locationQuery, setLocationQuery] = useState(""); const [locationResults, setLocationResults] = useState([]); const [searching, setSearching] = useState(false);
  const [savedLocations, setSavedLocations] = useState(() => { try { const stored = JSON.parse(localStorage.getItem("mausam-saved-locations")); return (stored || [defaultPlace, { ...defaultPlace, name: "Hyderabad", admin1: "Telangana" }, { ...defaultPlace, name: "New Delhi", admin1: "Delhi" }]).map((item) => typeof item === "string" ? { ...defaultPlace, name: item } : item); } catch { return [defaultPlace]; } });
  const [weather, setWeather] = useState(null); const [weatherLoading, setWeatherLoading] = useState(false); const [weatherError, setWeatherError] = useState("");
  const [modules, setModules] = useState(() => { try { return JSON.parse(localStorage.getItem("mausam-modules")) || { hero: true, personal: true, hourly: true, weekly: true, alerts: true, map: true }; } catch { return { hero: true, personal: true, hourly: true, weekly: true, alerts: true, map: true }; } });
  const persona = useMemo(() => personas.find(p=>p.id===personaId) || personas[0], [personaId]);
  const choosePersona = (id) => { setPersonaId(id); localStorage.setItem("mausam-persona", id); localStorage.setItem("mausam-seen", "true"); setOnboarding(false); };
  const chooseLocation = (place) => { const nextPlace = typeof place === "string" ? (savedLocations.find((item) => item.name === place) || { ...defaultPlace, name: place }) : place; setSelectedPlace(nextPlace); localStorage.setItem("mausam-location-place", JSON.stringify(nextPlace)); localStorage.setItem("mausam-location", nextPlace.name); const next = [nextPlace, ...savedLocations.filter((item)=>item.name !== nextPlace.name)].slice(0, 6); setSavedLocations(next); localStorage.setItem("mausam-saved-locations", JSON.stringify(next)); setShowLocationSearch(false); setLocationQuery(""); };
  useEffect(() => { if (locationQuery.trim().length < 2) { setLocationResults([]); return undefined; } let cancelled = false; const timer = setTimeout(async () => { setSearching(true); try { const results = await searchWeatherLocations(locationQuery.trim()); if (!cancelled) setLocationResults(results); } catch { const q = locationQuery.trim().toLowerCase(); const fallback = locationCatalog.filter(([name, area]) => `${name} ${area}`.toLowerCase().includes(q)).map(([name, area]) => ({ ...defaultPlace, name, admin1: area.split(",")[0] })); if (!cancelled) setLocationResults(fallback); } finally { if (!cancelled) setSearching(false); } }, 300); return () => { cancelled = true; clearTimeout(timer); }; }, [locationQuery]);
  useEffect(() => { let cancelled = false; setWeatherLoading(true); setWeatherError(""); fetchWeather(selectedPlace).then((result) => { if (!cancelled) setWeather(result); }).catch(() => { if (!cancelled) { setWeather(mockWeather); setWeatherError("Live weather unavailable · showing fallback data"); } }).finally(() => { if (!cancelled) setWeatherLoading(false); }); return () => { cancelled = true; }; }, [selectedPlace]);
  useEffect(() => { document.body.classList.toggle("dark-mode", dark); document.body.dataset.theme = theme; localStorage.setItem("mausam-theme", theme); }, [dark, theme]);
  const Lifestyle = persona.id === "fitness" ? FitnessCard : persona.id === "health" ? HealthCard : persona.id === "travel" ? TravelCard : persona.id === "beach" ? BeachCard : (props) => <GenericCard persona={persona} {...props}/>;
  const navTargets = { Home: "hero-weather-card", Forecast: "hourly-forecast", Map: "weather-map", Alerts: "alerts-section", "Saved Places": "saved-place-vijayawada" };
  const navigate = (x) => { setActiveNav(x); setMobileMenu(false); if (window.innerWidth <= 600) { requestAnimationFrame(() => { const main = document.querySelector(".main-content"); if (main) main.style.left = "25px"; }); return; } const target = document.querySelector(`[data-testid="${navTargets[x]}"]`); if (target) window.scrollTo({ top: Math.max(0, target.getBoundingClientRect().top + window.scrollY - 82), behavior: "smooth" }); };
  const saveModules = () => { localStorage.setItem("mausam-modules", JSON.stringify(modules)); setCustomize(false); };
  return <div className="app-shell"><AnimatePresence>{onboarding && <Onboarding onChoose={choosePersona} onSkip={()=>{localStorage.setItem("mausam-seen","true");setOnboarding(false)}} />}</AnimatePresence>
    <header className="topbar"><div className="brand"><span className="brand-mark"><Sun size={18}/></span><span>mausam</span><small>IMD / MoES</small></div><nav className={mobileMenu?"open":""}>{["Home","Forecast","Map","Alerts","Saved Places"].map(x=><button className={activeNav===x?"nav-active":""} key={x} onClick={()=>navigate(x)} data-testid={`nav-${x.toLowerCase().replace(" ", "-")}`}>{x}</button>)}</nav><div className="top-actions"><button className="location-picker" onClick={()=>setShowLocationSearch(true)} data-testid="location-selector"><MapPin size={15}/> {location} <ChevronDown size={14}/></button><div className="theme-picker-wrap"><IconButton label="Choose visual theme" onClick={()=>setShowThemes(!showThemes)} testid="theme-picker-button"><Palette size={18}/></IconButton>{showThemes && <div className="theme-menu" data-testid="theme-menu"><span className="theme-menu-label">VISUAL MOOD</span>{[["editorial","Storm glass","#5ea7aa"],["imd","Clean IMD","#1261a0"],["midnight","Midnight weather","#17253e"]].map(([id,label,color])=><button className={theme===id?"selected":""} key={id} onClick={()=>{setTheme(id);setDark(id==="midnight");setShowThemes(false)}} data-testid={`theme-option-${id}`}><i style={{background:color}} /><span>{label}</span>{theme===id && <b>✓</b>}</button>)}</div>}</div><IconButton label="Toggle dark mode" onClick={()=>setDark(!dark)} testid="dark-mode-toggle">{dark?<Sun size={18}/>:<Moon size={18}/>}</IconButton><IconButton label="Open notifications" onClick={()=>setShowNotifications(!showNotifications)} testid="notification-button"><Bell size={18}/><i className="notification-dot"/></IconButton><IconButton label="Open profile" onClick={()=>setShowProfile(!showProfile)} testid="profile-button"><span className="avatar">T</span></IconButton><IconButton label="Open menu" onClick={()=>setMobileMenu(!mobileMenu)} testid="mobile-menu-button"><Menu size={20}/></IconButton></div>{showNotifications && <div className="header-popover" data-testid="notification-panel"><b>Live weather sources</b><span>{weather?.current?.condition_label || "Current conditions"} in {location}</span><span>Official IMD warnings and UV data are not connected yet</span></div>}{showProfile && <div className="header-popover profile-popover" data-testid="profile-panel"><b>Tejeswar</b><span>Outdoor fitness profile</span><button onClick={()=>setCustomize(true)} data-testid="profile-preferences-button">Open preferences</button></div>}</header>
    <main className="main-content"><div className="welcome-row"><div><span className="eyebrow">THURSDAY, 24 OCTOBER 2024 / 4:42 PM</span><h2>Good afternoon, Tejeswar <span>👋</span></h2><p data-testid="persona-note">{persona.note} · Personalized for <b>{persona.label}</b></p></div><button className="customize-button" onClick={()=>setCustomize(true)} data-testid="customize-dashboard-button"><Settings2 size={16}/> Personalize dashboard</button></div><div className="persona-switcher" data-testid="persona-switcher">{personas.map(({id,short,icon:I})=><button className={id===personaId?"active":""} key={id} onClick={()=>choosePersona(id)} data-testid={`persona-switch-${id}`}><I size={16}/><span>{short}</span></button>)}</div>{weatherError && <div className="weather-inline-error" data-testid="weather-error">{weatherError}</div>}<div className="dashboard-grid">{modules.hero && <Hero dark={dark} location={location} weather={weather} loading={weatherLoading}/>} {modules.personal && <Lifestyle weather={weather}/>}</div>{modules.personal && <Recommendation persona={persona} weather={weather} location={location}/>}<div className="lower-grid"><div>{modules.hourly && <Hourly weather={weather}/>} {modules.map && <WeatherMap location={location}/>}</div><div>{modules.weekly && <Weekly weather={weather}/>} {modules.alerts && <Alerts weather={weather}/>}</div></div><section className="saved-row"><div><span className="eyebrow">YOUR PLACES</span><h2>Saved locations</h2></div><button className="add-place" onClick={()=>setShowLocationSearch(true)} data-testid="add-location-button"><Plus size={16}/> Add location</button><div className="place-cards">{savedLocations.map((place,index)=><div className={`place-card ${place.name===location?"current":""}`} key={place.name} onClick={()=>chooseLocation(place)} data-testid={`saved-place-${place.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`}><MapPin size={15}/><b>{place.name}</b><span>{index===0 && place.name===location ? "Live weather selected" : "Tap to view weather"}</span></div>)}</div></section></main>
    {showLocationSearch && <LocationSearch query={locationQuery} setQuery={setLocationQuery} results={locationResults} searching={searching} onSelect={chooseLocation} onClose={()=>{setShowLocationSearch(false);setLocationQuery("")}} />}
    {customize && <div className="modal-backdrop"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="customize-modal"><div className="modal-head"><div><span className="eyebrow">PERSONALIZE</span><h2>Make it yours</h2></div><IconButton label="Close customization" onClick={()=>setCustomize(false)} testid="close-customize-button"><X size={20}/></IconButton></div><p>Choose the signals you want at the top of your dashboard.</p>{[["Hero weather","hero"],["Personal recommendation","personal"],["Hourly forecast","hourly"],["7-day outlook","weekly"],["Alerts","alerts"],["Weather map","map"]].map(([x,key])=><label key={x} className="toggle-row" data-testid={`customize-row-${key}`}><span>{x}</span><input type="checkbox" checked={modules[key]} onChange={()=>setModules({...modules,[key]:!modules[key]})}/><i /></label>)}<button className="primary-button full" onClick={saveModules} data-testid="save-customize-button">Save dashboard</button></motion.div></div>}
  </div>;
}
export default App;