import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  Activity, AirVent, Bell, ChevronDown, CloudRain, Droplets, Eye, Gauge,
  Globe2, HeartPulse, Leaf, MapPin, Menu, Moon, MoreHorizontal, Navigation,
  Palette, Plus, Search, Settings2, ShieldAlert, ShipWheel, Sun, Sunrise, Sunset,
  Thermometer, UserRound, Waves, Wind, X, Zap
} from "lucide-react";
import "@/App.css";

const personas = [
  { id: "fitness", label: "Outdoor fitness", short: "Fitness", icon: Activity, color: "orange", note: "Your best window for movement" },
  { id: "health", label: "Health & wellness", short: "Health", icon: HeartPulse, color: "rose", note: "Breathe easier, plan smarter" },
  { id: "travel", label: "Travel", short: "Travel", icon: Globe2, color: "blue", note: "Know before you go" },
  { id: "beach", label: "Beach & surf", short: "Beach", icon: Waves, color: "cyan", note: "Read the rhythm of the coast" },
  { id: "family", label: "Family", short: "Family", icon: UserRound, color: "violet", note: "Good days start outdoors" },
  { id: "agriculture", label: "Agriculture", short: "Farm", icon: Leaf, color: "green", note: "Signals for every growing day" },
  { id: "commute", label: "Daily commute", short: "Commute", icon: Navigation, color: "amber", note: "Leave with confidence" },
  { id: "events", label: "Events", short: "Events", icon: Zap, color: "pink", note: "Make plans that hold" },
];

const hours = [["Now", "28°", Sun], ["4 PM", "29°", Sun], ["5 PM", "28°", CloudRain], ["6 PM", "27°", CloudRain], ["7 PM", "26°", CloudRain], ["8 PM", "25°", Moon]];
const days = [["Mon", "31°", "24°", Sun, "8%"], ["Tue", "30°", "23°", Sun, "12%"], ["Wed", "28°", "22°", CloudRain, "58%"], ["Thu", "27°", "22°", CloudRain, "70%"], ["Fri", "31°", "24°", Sun, "18%"]];
const locationCatalog = [
  ["Vijayawada", "Andhra Pradesh, India"], ["Hyderabad", "Telangana, India"], ["New Delhi", "Delhi, India"], ["Mumbai", "Maharashtra, India"], ["Bengaluru", "Karnataka, India"], ["Chennai", "Tamil Nadu, India"], ["Kolkata", "West Bengal, India"], ["Pune", "Maharashtra, India"], ["Visakhapatnam", "Andhra Pradesh, India"], ["Rajahmundry", "East Godavari, Andhra Pradesh, India"], ["Rajamahendravaram", "East Godavari, Andhra Pradesh, India"], ["Kakinada", "Kakinada district, Andhra Pradesh, India"], ["Amalapuram", "Konaseema district, Andhra Pradesh, India"], ["Ravulapalem", "Konaseema district, Andhra Pradesh, India"], ["Mandapeta", "Konaseema district, Andhra Pradesh, India"], ["Ramachandrapuram", "Konaseema district, Andhra Pradesh, India"], ["Mummidivaram", "Konaseema district, Andhra Pradesh, India"], ["Atreyapuram", "Konaseema district, Andhra Pradesh, India"], ["Alamuru", "Konaseema district, Andhra Pradesh, India"], ["Kothapeta", "Konaseema district, Andhra Pradesh, India"], ["Draksharamam", "Konaseema district, Andhra Pradesh, India"], ["Samalkota", "Kakinada district, Andhra Pradesh, India"], ["Peddapuram", "Kakinada district, Andhra Pradesh, India"], ["Pithapuram", "Kakinada district, Andhra Pradesh, India"], ["Tuni", "Kakinada district, Andhra Pradesh, India"], ["Anaparthi", "East Godavari, Andhra Pradesh, India"], ["Rajanagaram", "East Godavari, Andhra Pradesh, India"], ["Jaggampeta", "Kakinada district, Andhra Pradesh, India"], ["Gokavaram", "East Godavari, Andhra Pradesh, India"], ["Seethanagaram", "East Godavari, Andhra Pradesh, India"], ["Devipatnam", "Alluri Sitharama Raju district, Andhra Pradesh, India"], ["Rampachodavaram", "Alluri Sitharama Raju district, Andhra Pradesh, India"], ["Maredumilli", "Alluri Sitharama Raju district, Andhra Pradesh, India"], ["Polavaram", "Eluru district, Andhra Pradesh, India"], ["Kovvur", "West Godavari, Andhra Pradesh, India"], ["Nidadavole", "West Godavari, Andhra Pradesh, India"], ["Tanuku", "West Godavari, Andhra Pradesh, India"], ["Tadepalligudem", "West Godavari, Andhra Pradesh, India"], ["Bhimavaram", "West Godavari, Andhra Pradesh, India"], ["Palakollu", "West Godavari, Andhra Pradesh, India"], ["Narasapur", "West Godavari, Andhra Pradesh, India"], ["Eluru", "Eluru district, Andhra Pradesh, India"], ["Guntur", "Andhra Pradesh, India"], ["Tirupati", "Andhra Pradesh, India"], ["Goa", "India"], ["London", "England, United Kingdom"], ["New York", "New York, United States"], ["San Francisco", "California, United States"], ["Dubai", "United Arab Emirates"], ["Singapore", "Singapore"], ["Tokyo", "Japan"], ["Sydney", "New South Wales, Australia"], ["Paris", "France"], ["Toronto", "Ontario, Canada"], ["Berlin", "Germany"], ["Cape Town", "South Africa"], ["Bangkok", "Thailand"], ["Bali", "Indonesia"]
];
const glassGlobeUrl = "https://static.prod-images.emergentagent.com/jobs/242c255e-7b43-47bc-afec-4341caa17fe3/images/844aec80732e2009971269792101b9f4cc7840b02f2f594e23e10d8c446ed047.jpeg";

function IconButton({ children, label, onClick, testid }) { return <button className="icon-button" aria-label={label} title={label} data-testid={testid} onClick={onClick}>{children}</button>; }

function LocationSearch({ query, setQuery, results, onSelect, onClose }) {
  return <div className="location-modal-backdrop"><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="location-modal" data-testid="location-search-modal"><div className="location-modal-head"><div><span className="eyebrow">ADD A PLACE</span><h2>Where next?</h2></div><IconButton label="Close location search" onClick={onClose} testid="close-location-search-button"><X size={20}/></IconButton></div><div className="location-search-field"><Search size={18}/><input autoFocus value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search cities, places, or regions" data-testid="location-search-input"/><kbd>⌘ K</kbd></div><p className="location-search-note">Search the Mausam location directory. Select a result to add it to your places.</p><div className="location-results" data-testid="location-search-results">{results.length ? results.map(([name,area])=><button key={`${name}-${area}`} onClick={()=>onSelect(name)} data-testid={`location-result-${name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`}><span className="result-pin"><MapPin size={16}/></span><span><b>{name}</b><small>{area}</small></span><ChevronDown size={16}/></button>) : <div className="no-location-results" data-testid="no-location-results"><Search size={18}/><span>No places found. Try a city or region name.</span></div>}</div><div className="location-modal-foot"><Globe2 size={14}/> Worldwide directory · Google Places can be connected later for unlimited results</div></motion.div></div>;
}

function Onboarding({ onChoose, onSkip }) {
  const [selected, setSelected] = useState(["fitness"]);
  const toggle = (id) => setSelected((items) => items.includes(id) ? items.filter((x) => x !== id) : [...items, id]);
  return <div className="onboarding-backdrop"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="onboarding">
    <div className="onboarding-mark"><Sun size={22} /></div><span className="eyebrow">MAUSAM / YOUR WEATHER INTELLIGENCE</span>
    <h1>How do you use<br /><em>weather?</em></h1><p className="onboarding-copy">Tell us what matters to you. We&apos;ll make your forecast feel personal.</p>
    <div className="persona-grid">{personas.map(({ id, label, icon: I }) => <button key={id} className={`persona-option ${selected.includes(id) ? "selected" : ""}`} data-testid={`onboarding-persona-${id}`} onClick={() => toggle(id)}><I size={18} /><span>{label}</span>{selected.includes(id) && <span className="check">✓</span>}</button>)}</div>
    <div className="onboarding-actions"><button className="text-button" data-testid="onboarding-skip-button" onClick={onSkip}>Skip for now</button><button className="primary-button" data-testid="onboarding-continue-button" onClick={() => onChoose(selected[0] || "fitness")}>Build my dashboard <span>→</span></button></div>
  </motion.div></div>;
}

function Hero({ dark, location }) { return <motion.section layout className="hero panel" data-testid="hero-weather-card">
  <div className="globe-stage" aria-hidden="true"><div className="globe-halo" /><img src={glassGlobeUrl} alt="" /></div>
  <div className="hero-sky"><div className="sun-disc" /><div className="cloud cloud-one" /><div className="cloud cloud-two" /><div className="hero-lines" /><div className="weather-motion" data-testid="weather-motion" data-weather-state="partly-cloudy"><div className="rain-layer">{Array.from({length:14}, (_,i)=><i key={i} style={{left:`${8+(i*7)%90}%`, animationDelay:`-${(i%6)*.55}s`, animationDuration:`${1.5+(i%4)*.28}s`}} />)}</div><div className="lightning-flash" /></div></div>
  <div className="hero-top"><div><span className="eyebrow light">CURRENT CONDITIONS / 16:42 IST</span><h1 data-testid="hero-location">{location}</h1><p className="hero-condition" data-testid="hero-condition">Partly cloudy <span>•</span> Feels like 30°</p></div><div className="hero-temp" data-testid="hero-temperature">28°<small>C</small></div></div>
  <div className="hero-bottom"><div className="hero-summary"><span className="weather-icon"><Sun size={30} /></span><span>Good afternoon, Tejeswar <b>👋</b></span></div><div className="hero-metrics">{[[Droplets,"Humidity","72%"],[Wind,"Wind","14 km/h"],[Eye,"Visibility","8 km"],[Sun,"UV index","6 / High"]].map(([I, k, v]) => <div className="hero-metric" key={k} data-testid={`hero-metric-${k.toLowerCase().replace(" ", "-")}`}><I size={16} /><span>{k}</span><strong>{v}</strong></div>)}</div></div>
</motion.section>; }

function FitnessCard() { return <motion.section layout className="panel lifestyle fitness-card" data-testid="fitness-module"><div className="module-heading"><div><span className="eyebrow orange">OUTDOOR FITNESS</span><h2>Best time to run</h2></div><span className="score orange-score" data-testid="workout-score">87<span>/100</span></span></div><div className="run-window"><div><strong>6:00 AM – 8:00 AM</strong><p><span className="status-dot" /> Excellent conditions</p></div><div className="runner-visual"><Activity size={42} /><div className="track"><i /><i /><i /></div></div></div><div className="mini-stats">{[[Thermometer,"Temp","23°"],[Droplets,"Humidity","61%"],[Sun,"UV index","2"],[Wind,"Wind","9 km/h"]].map(([I,k,v]) => <div key={k} data-testid={`fitness-${k.toLowerCase().replace(" ", "-")}`}><I size={16}/><small>{k}</small><b>{v}</b></div>)}</div><p className="insight"><Zap size={15}/> Cool temperatures and moderate wind make this morning ideal for outdoor exercise.</p></motion.section>; }

function HealthCard() { return <motion.section layout className="panel lifestyle health-card" data-testid="health-module"><div className="module-heading"><div><span className="eyebrow rose">HEALTH WEATHER</span><h2>Keep your air day-ready</h2></div><span className="score rose-score">72<span>/100</span></span></div><div className="health-readings"><div className="aqi-ring"><strong>82</strong><span>AQI</span></div><div><b>Moderate</b><p>Comfortable for most people</p><div className="progress"><i /></div></div></div><div className="health-row"><span><Leaf size={15}/> Pollen <b>Low</b></span><span><Sun size={15}/> UV <b>High</b></span><span><Droplets size={15}/> Humidity <b>72%</b></span></div><p className="alert-note"><ShieldAlert size={16}/> High UV between 11 AM – 3 PM. Consider limiting prolonged exposure.</p></motion.section>; }

function TravelCard() { return <motion.section layout className="panel lifestyle travel-card" data-testid="travel-module"><div className="module-heading"><div><span className="eyebrow blue">TRAVEL WEATHER</span><h2>London <span className="flag">🇬🇧</span></h2></div><IconButton label="More travel options" testid="travel-more-button"><MoreHorizontal size={20}/></IconButton></div><div className="travel-main"><div><strong>18°</strong><span>Light rain</span></div><div className="travel-facts"><span><CloudRain size={15}/> 70% rain</span><span><Wind size={15}/> 18 km/h</span></div></div><div className="packing"><span>🧳</span><div><b>Pack a rain jacket</b><small>Heavy rain expected tomorrow evening</small></div><ChevronDown size={17}/></div></motion.section>; }

function BeachCard() { return <motion.section layout className="panel lifestyle beach-card" data-testid="beach-module"><div className="wave-art"><Waves size={82}/></div><div className="module-heading"><div><span className="eyebrow cyan">BEACH CONDITIONS</span><h2>Read the tide</h2></div><span className="score cyan-score">91<span>/100</span></span></div><div className="beach-stats"><span><b>27°</b>Water temp</span><span><b>1.4m</b>Wave height</span><span><b>12 km/h</b>Wind</span></div><p className="tide-line"><span>Low tide <b>10:45 AM</b></span><span>High tide <b>4:20 PM</b></span></p></motion.section>; }

function GenericCard({ persona }) { const config = { family: ["FAMILY WEATHER", "Good days start outdoors", "UV is gentle until 5 PM. A great window for a park visit.", "82%", "Family comfort"], agriculture: ["FARM WEATHER", "A good day to plant", "12 mm rain expected tomorrow. Soil moisture is in the sweet spot.", "76%", "Planting window"], commute: ["MORNING COMMUTE", "Travel carefully", "60% rain probability along your route from 7:30 – 9:00 AM.", "4 km", "Visibility"], events: ["OUTDOOR EVENT", "Saturday looks promising", "26° – 31° with only 18% rain probability. Make plans that hold.", "86/100", "Comfort index"] }[persona.id] || ["YOUR OUTLOOK", persona.note, "The day is looking comfortable for your plans.", "Good", "Conditions"]; return <motion.section layout className={`panel lifestyle generic-card ${persona.color}`} data-testid={`${persona.id}-module`}><span className="eyebrow">{config[0]}</span><h2>{config[1]}</h2><p>{config[2]}</p><div className="generic-bottom"><div><b>{config[3]}</b><small>{config[4]}</small></div><div className="spark-bars">{[20,42,31,62,48,78,58].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div></div></motion.section>; }

function Hourly() { return <section className="section-block" data-testid="hourly-forecast"><div className="section-title"><div><span className="eyebrow">THE DAY AHEAD</span><h2>Hourly forecast</h2></div><button className="link-button" data-testid="hourly-view-all-button">View 24 hours <span>→</span></button></div><div className="hourly-strip">{hours.map(([t,temp,I], i) => <div className={`hour ${i===0?"active":""}`} key={t} data-testid={`hour-${t.toLowerCase().replace(" ", "-")}`}><small>{t}</small><I size={22}/><b>{temp}</b><span>{i===2||i===3?"40%":"—"}</span></div>)}</div></section>; }

function Weekly() { return <section className="panel weekly" data-testid="weekly-forecast"><div className="section-title"><div><span className="eyebrow">EXTENDED OUTLOOK</span><h2>Next 5 days</h2></div><IconButton label="More forecast options" testid="weekly-more-button"><MoreHorizontal size={20}/></IconButton></div>{days.map(([d,hi,lo,I,rain]) => <div className="day-row" key={d} data-testid={`forecast-${d.toLowerCase()}`}><b>{d}</b><I size={19}/><span className="rain-chance">{rain} rain</span><div className="temp-bar"><i style={{width:`${parseInt(hi)+5}%`}} /></div><strong>{hi}</strong><span className="low">{lo}</span></div>)}</section>; }

function WeatherMap({ location }) { const [layer, setLayer] = useState("Rainfall"); return <section className="panel map-panel" data-testid="weather-map"><div className="section-title"><div><span className="eyebrow">LIVE LAYERS / MOCK IMD FEED</span><h2>Weather map</h2></div><button className="map-location" data-testid="map-location-button"><MapPin size={15}/> {location}</button></div><div className="map-canvas"><div className="map-grid"/><div className="map-road road-one"/><div className="map-road road-two"/><div className="radar radar-one"/><div className="radar radar-two"/><div className="map-pin"><MapPin size={22}/><span>28°</span></div><div className="map-label label-one">Guntur</div><div className="map-label label-two">Eluru</div></div><div className="layer-tabs">{["Temperature","Rainfall","Wind","AQI","Satellite"].map(x=><button className={layer===x?"active":""} key={x} onClick={()=>setLayer(x)} data-testid={`map-layer-${x.toLowerCase()}`}>{x}</button>)}</div></section>; }

function Alerts() { return <section className="panel alerts" data-testid="alerts-section"><div className="section-title"><div><span className="eyebrow orange">IMD ALERT CENTER</span><h2>Stay weather-aware</h2></div><span className="alert-count" data-testid="alert-count">2 new</span></div><div className="alert-item warning alert-feature" data-testid="severe-weather-alert"><div className="alert-icon"><CloudRain size={18}/></div><div><b>Heavy rain alert</b><p>Expected in your area between 6 PM and 10 PM.</p></div><ChevronDown size={18}/></div><div className="alert-item info"><div className="alert-icon"><Sun size={18}/></div><div><b>UV advisory</b><p>High UV index through the afternoon. Stay hydrated.</p></div><ChevronDown size={18}/></div><button className="outline-button" data-testid="view-alerts-button">View all alerts <span>→</span></button></section>; }

function App() {
  const [personaId, setPersonaId] = useState(localStorage.getItem("mausam-persona") || "fitness");
  const [onboarding, setOnboarding] = useState(localStorage.getItem("mausam-seen") !== "true");
  const [dark, setDark] = useState(false); const [customize, setCustomize] = useState(false); const [mobileMenu, setMobileMenu] = useState(false); const [activeNav, setActiveNav] = useState("Home"); const [showThemes, setShowThemes] = useState(false);
  const [theme, setTheme] = useState(localStorage.getItem("mausam-theme") || "editorial");
  const [location, setLocation] = useState(localStorage.getItem("mausam-location") || "Vijayawada"); const [showNotifications, setShowNotifications] = useState(false); const [showProfile, setShowProfile] = useState(false); const [showLocationSearch, setShowLocationSearch] = useState(false); const [locationQuery, setLocationQuery] = useState("");
  const [savedLocations, setSavedLocations] = useState(() => { try { return JSON.parse(localStorage.getItem("mausam-saved-locations")) || ["Vijayawada", "Hyderabad", "New Delhi"]; } catch { return ["Vijayawada", "Hyderabad", "New Delhi"]; } });
  const [modules, setModules] = useState(() => { try { return JSON.parse(localStorage.getItem("mausam-modules")) || { hero: true, personal: true, hourly: true, weekly: true, alerts: true, map: true }; } catch { return { hero: true, personal: true, hourly: true, weekly: true, alerts: true, map: true }; } });
  const persona = useMemo(() => personas.find(p=>p.id===personaId) || personas[0], [personaId]);
  const choosePersona = (id) => { setPersonaId(id); localStorage.setItem("mausam-persona", id); localStorage.setItem("mausam-seen", "true"); setOnboarding(false); };
  const chooseLocation = (name) => { setLocation(name); localStorage.setItem("mausam-location", name); const next = [name, ...savedLocations.filter((item)=>item !== name)].slice(0, 6); setSavedLocations(next); localStorage.setItem("mausam-saved-locations", JSON.stringify(next)); setShowLocationSearch(false); setLocationQuery(""); };
  const locationResults = useMemo(() => { const q = locationQuery.trim().toLowerCase(); return (q ? locationCatalog.filter(([name, area]) => `${name} ${area}`.toLowerCase().includes(q)) : locationCatalog.slice(0, 8)); }, [locationQuery]);
  useEffect(() => { document.body.classList.toggle("dark-mode", dark); document.body.dataset.theme = theme; localStorage.setItem("mausam-theme", theme); }, [dark, theme]);
  const Lifestyle = persona.id === "fitness" ? FitnessCard : persona.id === "health" ? HealthCard : persona.id === "travel" ? TravelCard : persona.id === "beach" ? BeachCard : () => <GenericCard persona={persona}/>;
  const navTargets = { Home: "hero-weather-card", Forecast: "hourly-forecast", Map: "weather-map", Alerts: "alerts-section", "Saved Places": "saved-place-vijayawada" };
  const navigate = (x) => { setActiveNav(x); setMobileMenu(false); if (window.innerWidth <= 600) { requestAnimationFrame(() => { const main = document.querySelector(".main-content"); if (main) main.style.left = "25px"; }); return; } const target = document.querySelector(`[data-testid="${navTargets[x]}"]`); if (target) window.scrollTo({ top: Math.max(0, target.getBoundingClientRect().top + window.scrollY - 82), behavior: "smooth" }); };
  const saveModules = () => { localStorage.setItem("mausam-modules", JSON.stringify(modules)); setCustomize(false); };
  return <div className="app-shell"><AnimatePresence>{onboarding && <Onboarding onChoose={choosePersona} onSkip={()=>{localStorage.setItem("mausam-seen","true");setOnboarding(false)}} />}</AnimatePresence>
    <header className="topbar"><div className="brand"><span className="brand-mark"><Sun size={18}/></span><span>mausam</span><small>IMD / MoES</small></div><nav className={mobileMenu?"open":""}>{["Home","Forecast","Map","Alerts","Saved Places"].map(x=><button className={activeNav===x?"nav-active":""} key={x} onClick={()=>navigate(x)} data-testid={`nav-${x.toLowerCase().replace(" ", "-")}`}>{x}</button>)}</nav><div className="top-actions"><button className="location-picker" onClick={()=>setShowLocationSearch(true)} data-testid="location-selector"><MapPin size={15}/> {location} <ChevronDown size={14}/></button><div className="theme-picker-wrap"><IconButton label="Choose visual theme" onClick={()=>setShowThemes(!showThemes)} testid="theme-picker-button"><Palette size={18}/></IconButton>{showThemes && <div className="theme-menu" data-testid="theme-menu"><span className="theme-menu-label">VISUAL MOOD</span>{[["editorial","Storm glass","#5ea7aa"],["imd","Clean IMD","#1261a0"],["midnight","Midnight weather","#17253e"]].map(([id,label,color])=><button className={theme===id?"selected":""} key={id} onClick={()=>{setTheme(id);setDark(id==="midnight");setShowThemes(false)}} data-testid={`theme-option-${id}`}><i style={{background:color}} /><span>{label}</span>{theme===id && <b>✓</b>}</button>)}</div>}</div><IconButton label="Toggle dark mode" onClick={()=>setDark(!dark)} testid="dark-mode-toggle">{dark?<Sun size={18}/>:<Moon size={18}/>}</IconButton><IconButton label="Open notifications" onClick={()=>setShowNotifications(!showNotifications)} testid="notification-button"><Bell size={18}/><i className="notification-dot"/></IconButton><IconButton label="Open profile" onClick={()=>setShowProfile(!showProfile)} testid="profile-button"><span className="avatar">T</span></IconButton><IconButton label="Open menu" onClick={()=>setMobileMenu(!mobileMenu)} testid="mobile-menu-button"><Menu size={20}/></IconButton></div>{showNotifications && <div className="header-popover" data-testid="notification-panel"><b>2 weather updates</b><span>Heavy rain expected after 6 PM</span><span>UV advisory for your area</span></div>}{showProfile && <div className="header-popover profile-popover" data-testid="profile-panel"><b>Tejeswar</b><span>Outdoor fitness profile</span><button onClick={()=>setCustomize(true)} data-testid="profile-preferences-button">Open preferences</button></div>}</header>
    <main className="main-content"><div className="welcome-row"><div><span className="eyebrow">THURSDAY, 24 OCTOBER 2024 / 4:42 PM</span><h2>Good afternoon, Tejeswar <span>👋</span></h2><p data-testid="persona-note">{persona.note} · Personalized for <b>{persona.label}</b></p></div><button className="customize-button" onClick={()=>setCustomize(true)} data-testid="customize-dashboard-button"><Settings2 size={16}/> Customize dashboard</button></div><div className="persona-switcher" data-testid="persona-switcher">{personas.map(({id,short,icon:I})=><button className={id===personaId?"active":""} key={id} onClick={()=>choosePersona(id)} data-testid={`persona-switch-${id}`}><I size={16}/><span>{short}</span></button>)}</div><div className="dashboard-grid">{modules.hero && <Hero dark={dark} location={location}/>} {modules.personal && <Lifestyle />}</div><div className="lower-grid"><div>{modules.hourly && <Hourly />}{modules.map && <WeatherMap location={location}/>}</div><div>{modules.weekly && <Weekly />}{modules.alerts && <Alerts />}</div></div><section className="saved-row"><div><span className="eyebrow">YOUR PLACES</span><h2>Saved locations</h2></div><button className="add-place" onClick={()=>setShowLocationSearch(true)} data-testid="add-location-button"><Plus size={16}/> Add location</button><div className="place-cards">{savedLocations.map((place,index)=><div className={`place-card ${place===location?"current":""}`} key={place} onClick={()=>chooseLocation(place)} data-testid={`saved-place-${place.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`}><MapPin size={15}/><b>{place}</b><span>{index===0 && place===location ? "28° · Partly cloudy" : "Tap to view weather"}</span></div>)}</div></section></main>
    {showLocationSearch && <LocationSearch query={locationQuery} setQuery={setLocationQuery} results={locationResults} onSelect={chooseLocation} onClose={()=>{setShowLocationSearch(false);setLocationQuery("")}} />}
    {customize && <div className="modal-backdrop"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="customize-modal"><div className="modal-head"><div><span className="eyebrow">PERSONALIZE</span><h2>Make it yours</h2></div><IconButton label="Close customization" onClick={()=>setCustomize(false)} testid="close-customize-button"><X size={20}/></IconButton></div><p>Choose the signals you want at the top of your dashboard.</p>{[["Hero weather","hero"],["Personal recommendation","personal"],["Hourly forecast","hourly"],["7-day outlook","weekly"],["Alerts","alerts"],["Weather map","map"]].map(([x,key])=><label key={x} className="toggle-row" data-testid={`customize-row-${key}`}><span>{x}</span><input type="checkbox" checked={modules[key]} onChange={()=>setModules({...modules,[key]:!modules[key]})}/><i /></label>)}<button className="primary-button full" onClick={saveModules} data-testid="save-customize-button">Save dashboard</button></motion.div></div>}
  </div>;
}
export default App;